# Generated by Django 5.2.7 on 2025-10-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
